fix: algolia in ci

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -120,6 +120,14 @@ jobs:
           echo "Error: The GitHub secret of \"ALGOLIA_CRAWLER_API_KEY\" is not set."
           exit 1
 
+      - name: Check if the "ALGOLIA_CRAWLER_ID" GitHub secret is set
+        env:
+          SECRET_CHECK: ${{ secrets.ALGOLIA_CRAWLER_ID }}
+        if: ${{ env.SECRET_CHECK == '' }}
+        run: |
+          echo "Error: The GitHub secret of \"ALGOLIA_CRAWLER_ID\" is not set."
+          exit 1
+
       - name: Retrieve the docs build directory
         uses: actions/download-artifact@v4
         with:
@@ -144,14 +152,17 @@ jobs:
         run: npx tsx ./packages/docs/scripts/deploy.mts ${{ secrets.GITHUB_TOKEN }}
 
       - name: Run Algolia Crawler
-        if: steps.deploy-website.outputs.SHOULD_CRAWL == '1'
         env:
+          # From: https://crawler.algolia.com/admin/user/settings/
           ALGOLIA_CRAWLER_USER_ID: ${{ secrets.ALGOLIA_CRAWLER_USER_ID }}
           ALGOLIA_CRAWLER_API_KEY: ${{ secrets.ALGOLIA_CRAWLER_API_KEY }}
+
+          # From: https://crawler.algolia.com/admin/crawlers/TODO/settings
+          ALGOLIA_CRAWLER_ID: ${{ secrets.ALGOLIA_CRAWLER_ID }}
         run: |
           curl -X POST -H "Content-Type: application/json" \
             --user $ALGOLIA_CRAWLER_USER_ID:$ALGOLIA_CRAWLER_API_KEY \
-            "https://crawler.algolia.com/api/1/crawlers/$ALGOLIA_CRAWLER_USER_ID/reindex"
+            "https://crawler.algolia.com/api/1/crawlers/$ALGOLIA_CRAWLER_ID/reindex"
 
   discord:
     name: Discord Failure Notification
