chore: add ci validation

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -102,6 +102,14 @@ jobs:
           name: docs-build
           path: ./packages/docs/build
 
+      - name: Check if "DOCS_SSH_PRIVATE_KEY" secret is set
+        env:
+          SECRET_TO_CHECK: ${{ secrets.DOCS_SSH_PRIVATE_KEY }}
+        if: ${{ env.SECRET_TO_CHECK == '' }}
+        run: |
+          echo "Error: The GitHub secret of \"DOCS_SSH_PRIVATE_KEY\" is not set."
+          exit 1
+
       - name: Checkout the docs repository
         uses: actions/checkout@v4
         with:
